export const  ACADEMIC_INITIAL_STATE =  {
    degreeName: { 
      name: 'degreeName',
      label: 'degreeName',
      status: true,
      errorText: '',
      value: '',
      rules: ['isRequired'],
      fieldName: 'Degree Name',
      placeholder: 'Enter degree name',
    },
    board: { 
      name: 'board',
      label: 'Board',
      status: true,
      errorText: '',
      value: '',
      rules: ['isRequired'],
      fieldName: 'Board',
      placeholder: 'Enter board name',
    },
    university: { 
      name: 'university',
      label: 'University',
      status: true,
      errorText: '',
      value: '',
      rules: ['isRequired'],
      fieldName: 'University',
      placeholder: 'Enter university name',
    },
    marks: { 
      name: 'marks',
      label: 'Marks',
      status: true,
      errorText: '',
      value: '',
      rules: ['isRequired', 'isPositive'],
      fieldName: 'Marks',
      placeholder: 'Enter marks',
    },
    grade: { 
      name: 'grade',
      label: 'Grade',
      status: true,
      errorText: '',
      value: '',
      rules: ['isRequired'],
      fieldName: 'Grade',
      placeholder: 'Enter grade',
    },
  }