export const DEPENDENT_INITIAL_STATE = {
    name: { 
      name: 'name',
      label: 'Name',
      status: true,
      errorText: '',
      value: '',
      rules: [],
      fieldName: 'Name',
      placeholder: 'Enter name',
    },
    gender: { 
      name: 'gender',
      label: 'Gender',
      status: true,
      errorText: '',
      value: '',
      rules: [],
      fieldName: 'Gender',
      placeholder: 'Select gender',
    },
    relation: { 
      name: 'relation',
      label: 'Relation',
      status: true,
      errorText: '',
      value: '',
      rules: [],
      fieldName: 'Relation',
      placeholder: 'Select relation ',
    },
    contact: { 
      name: 'contact',
      label: 'Contact',
      status: true,
      errorText: '',
      value: '',
      rules: [],
      fieldName: 'Contact',
      placeholder: 'Enter contact',
    },
    dateOfBirth: { 
      name: 'dateOfBirth',
      label: 'Date Of Birth',
      status: true,
      errorText: '',
      value: '',
      rules: [],
      fieldName: 'Date Of Birth',
      placeholder: 'Select date of birth',
    },
  }