export const ACADEMIC_INITIAL_STATE = {
  organization: { 
    name: 'organization',
    label: 'Organization',
    status: true,
    errorText: '',
    value: '',
    rules: ['isRequired'],
    fieldName: 'Organization',
    placeholder: 'Enter organization',
  },
  designation: { 
    name: 'designation',
    label: 'Designation',
    status: true,
    errorText: '',
    value: '',
    rules: ['isRequired'],
    fieldName: 'Designation',
    placeholder: 'Enter designation',
  },
  duration: { 
    name: 'duration',
    label: 'Duration',
    status: true,
    errorText: '',
    value: '',
    rules: ['isRequired'],
    fieldName: 'Duration',
    placeholder: 'Enter duration',
  },
  leavingReason: { 
    name: 'leavingReason',
    label: 'Leaving Reason',
    status: true,
    errorText: '',
    value: '',
    rules: ['isRequired'],
    fieldName: 'Leaving Reason',
    placeholder: 'Enter leaving reason',
  },
  salary: { 
    name: 'salary',
    label: 'Salary',
    status: true,
    errorText: '',
    value: '',
    rules: ['isRequired', 'isPositive'],
    fieldName: 'Salary',
    placeholder: 'Enter salary',
  },
}