export const RESET_REDUCER = 'HRMS/Employees/List/RESET_REDUCER';

export const GET_EMPLOYEES = 'HRMS/Employees/List/GET_EMPLOYEES';
export const GET_EMPLOYEES_SUCCESS = 'HRMS/Employees/List/GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_FAIL = 'HRMS/Employees/List/GET_EMPLOYEES_FAIL'; 

export const DELETE_EMPLOYEE = 'HRMS/Employees/List/DELETE_EMPLOYEE';
export const DELETE_EMPLOYEE_SUCCESS = 'HRMS/Employees/List/DELETE_EMPLOYEE_SUCCESS';
export const DELETE_EMPLOYEE_FAIL = 'HRMS/Employees/List/DELETE_EMPLOYEE_FAIL';