const MONGO_URL =
  "mongodb+srv://bitbytes:bitbytes123@hr-system-5a8n4.mongodb.net/development?retryWrites=true&w=majority";
const { NODE_ENV } = process.env;

const GENDER_OPTIONS = [
  { key: "male", text: "Male", value: "Male" },
  { key: "female", text: "Female", value: "Female" }
];
const COUNTRY_OPTIONS = [
  { text: "Afghanistan", key: "af", value: "af" },
  { text: "Aland Islands", key: "ax", value: "ax" },
  { text: "Albania", key: "al", value: "al" },
  { text: "Algeria", key: "dz", value: "dz" },
  { text: "American Samoa", key: "as", value: "as" },
  { text: "Andorra", key: "ad", value: "ad" },
  { text: "Angola", key: "ao", value: "ao" },
  { text: "Anguilla", key: "ai", value: "ai" },
  { text: "Antigua", key: "ag", value: "ag" },
  { text: "Argentina", key: "ar", value: "ar" },
  { text: "Armenia", key: "am", value: "am" },
  { text: "Aruba", key: "aw", value: "aw" },
  { text: "Australia", key: "au", value: "au" },
  { text: "Austria", key: "at", value: "at" },
  { text: "Azerbaijan", key: "az", value: "az" },
  { text: "Bahamas", key: "bs", value: "bs" },
  { text: "Bahrain", key: "bh", value: "bh" },
  { text: "Bangladesh", key: "bd", value: "bd" },
  { text: "Barbados", key: "bb", value: "bb" },
  { text: "Belarus", key: "by", value: "by" },
  { text: "Belgium", key: "be", value: "be" },
  { text: "Belize", key: "bz", value: "bz" },
  { text: "Benin", key: "bj", value: "bj" },
  { text: "Bermuda", key: "bm", value: "bm" },
  { text: "Bhutan", key: "bt", value: "bt" },
  { text: "Bolivia", key: "bo", value: "bo" },
  { text: "Bosnia", key: "ba", value: "ba" },
  { text: "Botswana", key: "bw", value: "bw" },
  { text: "Bouvet Island", key: "bv", value: "bv" },
  { text: "Brazil", key: "br", value: "br" },
  { text: "British Virgin Islands", key: "vg", value: "vg" },
  { text: "Brunei", key: "bn", value: "bn" },
  { text: "Bulgaria", key: "bg", value: "bg" },
  { text: "Burkina Faso", key: "bf", value: "bf" },
  { text: "Burma", key: "mm", value: "mm", alias: "Myanmar" },
  { text: "Burundi", key: "bi", value: "bi" },
  { text: "Caicos Islands", key: "tc", value: "tc" },
  { text: "Cambodia", key: "kh", value: "kh" },
  { text: "Cameroon", key: "cm", value: "cm" },
  { text: "Canada", key: "ca", value: "ca" },
  { text: "Cape Verde", key: "cv", value: "cv" },
  { text: "Cayman Islands", key: "ky", value: "ky" },
  { text: "Central African Republic", key: "cf", value: "cf" },
  { text: "Chad", key: "td", value: "td" },
  { text: "Chile", key: "cl", value: "cl" },
  { text: "China", key: "cn", value: "cn" },
  { text: "Christmas Island", key: "cx", value: "cx" },
  { text: "Cocos Islands", key: "cc", value: "cc" },
  { text: "Colombia", key: "co", value: "co" },
  { text: "Comoros", key: "km", value: "km" },
  { text: "Congo", key: "cd", value: "cd" },
  { text: "Congo Brazzaville", key: "cg", value: "cg" },
  { text: "Cook Islands", key: "ck", value: "ck" },
  { text: "Costa Rica", key: "cr", value: "cr" },
  { text: "Cote Divoire", key: "ci", value: "ci" },
  { text: "Croatia", key: "hr", value: "hr" },
  { text: "Cuba", key: "cu", value: "cu" },
  { text: "Cyprus", key: "cy", value: "cy" },
  { text: "Czech Republic", key: "cz", value: "cz" },
  { text: "Denmark", key: "dk", value: "dk" },
  { text: "Djibouti", key: "dj", value: "dj" },
  { text: "Dominica", key: "dm", value: "dm" },
  { text: "Dominican Republic", key: "do", value: "do" },
  { text: "Ecuador", key: "ec", value: "ec" },
  { text: "Egypt", key: "eg", value: "eg" },
  { text: "El Salvador", key: "sv", value: "sv" },
  { text: "Equatorial Guinea", key: "gq", value: "gq" },
  { text: "Eritrea", key: "er", value: "er" },
  { text: "Estonia", key: "ee", value: "ee" },
  { text: "Ethiopia", key: "et", value: "et" },
  { text: "Europeanunion", key: "eu", value: "eu" },
  { text: "Falkland Islands", key: "fk", value: "fk" },
  { text: "Faroe Islands", key: "fo", value: "fo" },
  { text: "Fiji", key: "fj", value: "fj" },
  { text: "Finland", key: "fi", value: "fi" },
  { text: "France", key: "fr", value: "fr" },
  { text: "French Guiana", key: "gf", value: "gf" },
  { text: "French Polynesia", key: "pf", value: "pf" },
  { text: "French Territories", key: "tf", value: "tf" },
  { text: "Gabon", key: "ga", value: "ga" },
  { text: "Gambia", key: "gm", value: "gm" },
  { text: "Georgia", key: "ge", value: "ge" },
  { text: "Germany", key: "de", value: "de" },
  { text: "Ghana", key: "gh", value: "gh" },
  { text: "Gibraltar", key: "gi", value: "gi" },
  { text: "Greece", key: "gr", value: "gr" },
  { text: "Greenland", key: "gl", value: "gl" },
  { text: "Grenada", key: "gd", value: "gd" },
  { text: "Guadeloupe", key: "gp", value: "gp" },
  { text: "Guam", key: "gu", value: "gu" },
  { text: "Guatemala", key: "gt", value: "gt" },
  { text: "Guinea", key: "gn", value: "gn" },
  { text: "Guinea-Bissau", key: "gw", value: "gw" },
  { text: "Guyana", key: "gy", value: "gy" },
  { text: "Haiti", key: "ht", value: "ht" },
  { text: "Heard Island", key: "hm", value: "hm" },
  { text: "Honduras", key: "hn", value: "hn" },
  { text: "Hong Kong", key: "hk", value: "hk" },
  { text: "Hungary", key: "hu", value: "hu" },
  { text: "Iceland", key: "is", value: "is" },
  { text: "India", key: "in", value: "in" },
  { text: "Indian Ocean Territory", key: "io", value: "io" },
  { text: "Indonesia", key: "id", value: "id" },
  { text: "Iran", key: "ir", value: "ir" },
  { text: "Iraq", key: "iq", value: "iq" },
  { text: "Ireland", key: "ie", value: "ie" },
  { text: "Israel", key: "il", value: "il" },
  { text: "Italy", key: "it", value: "it" },
  { text: "Jamaica", key: "jm", value: "jm" },
  { text: "Jan Mayen", key: "sj", value: "sj", alias: "Svalbard" },
  { text: "Japan", key: "jp", value: "jp" },
  { text: "Jordan", key: "jo", value: "jo" },
  { text: "Kazakhstan", key: "kz", value: "kz" },
  { text: "Kenya", key: "ke", value: "ke" },
  { text: "Kiribati", key: "ki", value: "ki" },
  { text: "Kuwait", key: "kw", value: "kw" },
  { text: "Kyrgyzstan", key: "kg", value: "kg" },
  { text: "Laos", key: "la", value: "la" },
  { text: "Latvia", key: "lv", value: "lv" },
  { text: "Lebanon", key: "lb", value: "lb" },
  { text: "Lesotho", key: "ls", value: "ls" },
  { text: "Liberia", key: "lr", value: "lr" },
  { text: "Libya", key: "ly", value: "ly" },
  { text: "Liechtenstein", key: "li", value: "li" },
  { text: "Lithuania", key: "lt", value: "lt" },
  { text: "Luxembourg", key: "lu", value: "lu" },
  { text: "Macau", key: "mo", value: "mo" },
  { text: "Macedonia", key: "mk", value: "mk" },
  { text: "Madagascar", key: "mg", value: "mg" },
  { text: "Malawi", key: "mw", value: "mw" },
  { text: "Malaysia", key: "my", value: "my" },
  { text: "Maldives", key: "mv", value: "mv" },
  { text: "Mali", key: "ml", value: "ml" },
  { text: "Malta", key: "mt", value: "mt" },
  { text: "Marshall Islands", key: "mh", value: "mh" },
  { text: "Martinique", key: "mq", value: "mq" },
  { text: "Mauritania", key: "mr", value: "mr" },
  { text: "Mauritius", key: "mu", value: "mu" },
  { text: "Mayotte", key: "yt", value: "yt" },
  { text: "Mexico", key: "mx", value: "mx" },
  { text: "Micronesia", key: "fm", value: "fm" },
  { text: "Moldova", key: "md", value: "md" },
  { text: "Monaco", key: "mc", value: "mc" },
  { text: "Mongolia", key: "mn", value: "mn" },
  { text: "Montenegro", key: "me", value: "me" },
  { text: "Montserrat", key: "ms", value: "ms" },
  { text: "Morocco", key: "ma", value: "ma" },
  { text: "Mozambique", key: "mz", value: "mz" },
  { text: "Namibia", key: "na", value: "na" },
  { text: "Nauru", key: "nr", value: "nr" },
  { text: "Nepal", key: "np", value: "np" },
  { text: "Netherlands", key: "nl", value: "nl" },
  { text: "Netherlandsantilles", key: "an", value: "an" },
  { text: "New Caledonia", key: "nc", value: "nc" },
  { text: "New Guinea", key: "pg", value: "pg" },
  { text: "New Zealand", key: "nz", value: "nz" },
  { text: "Nicaragua", key: "ni", value: "ni" },
  { text: "Niger", key: "ne", value: "ne" },
  { text: "Nigeria", key: "ng", value: "ng" },
  { text: "Niue", key: "nu", value: "nu" },
  { text: "Norfolk Island", key: "nf", value: "nf" },
  { text: "North Korea", key: "kp", value: "kp" },
  { text: "Northern Mariana Islands", key: "mp", value: "mp" },
  { text: "Norway", key: "no", value: "no" },
  { text: "Oman", key: "om", value: "om" },
  { text: "Pakistan", key: "pk", value: "pk" },
  { text: "Palau", key: "pw", value: "pw" },
  { text: "Palestine", key: "ps", value: "ps" },
  { text: "Panama", key: "pa", value: "pa" },
  { text: "Paraguay", key: "py", value: "py" },
  { text: "Peru", key: "pe", value: "pe" },
  { text: "Philippines", key: "ph", value: "ph" },
  { text: "Pitcairn Islands", key: "pn", value: "pn" },
  { text: "Poland", key: "pl", value: "pl" },
  { text: "Portugal", key: "pt", value: "pt" },
  { text: "Puerto Rico", key: "pr", value: "pr" },
  { text: "Qatar", key: "qa", value: "qa" },
  { text: "Reunion", key: "re", value: "re" },
  { text: "Romania", key: "ro", value: "ro" },
  { text: "Russia", key: "ru", value: "ru" },
  { text: "Rwanda", key: "rw", value: "rw" },
  { text: "Saint Helena", key: "sh", value: "sh" },
  { text: "Saint Kitts and Nevis", key: "kn", value: "kn" },
  { text: "Saint Lucia", key: "lc", value: "lc" },
  { text: "Saint Pierre", key: "pm", value: "pm" },
  { text: "Saint Vincent", key: "vc", value: "vc" },
  { text: "Samoa", key: "ws", value: "ws" },
  { text: "San Marino", key: "sm", value: "sm" },
  { text: "Sandwich Islands", key: "gs", value: "gs" },
  { text: "Sao Tome", key: "st", value: "st" },
  { text: "Saudi Arabia", key: "sa", value: "sa" },
  { text: "Scotland", key: "sct", value: "sct" },
  { text: "Senegal", key: "sn", value: "sn" },
  { text: "Serbia", key: "cs", value: "cs" },
  { text: "Serbia", key: "rs", value: "rs" },
  { text: "Seychelles", key: "sc", value: "sc" },
  { text: "Sierra Leone", key: "sl", value: "sl" },
  { text: "Singapore", key: "sg", value: "sg" },
  { text: "Slovakia", key: "sk", value: "sk" },
  { text: "Slovenia", key: "si", value: "si" },
  { text: "Solomon Islands", key: "sb", value: "sb" },
  { text: "Somalia", key: "so", value: "so" },
  { text: "South Africa", key: "za", value: "za" },
  { text: "South Korea", key: "kr", value: "kr" },
  { text: "Spain", key: "es", value: "es" },
  { text: "Sri Lanka", key: "lk", value: "lk" },
  { text: "Sudan", key: "sd", value: "sd" },
  { text: "Suriname", key: "sr", value: "sr" },
  { text: "Swaziland", key: "sz", value: "sz" },
  { text: "Sweden", key: "se", value: "se" },
  { text: "Switzerland", key: "ch", value: "ch" },
  { text: "Syria", key: "sy", value: "sy" },
  { text: "Taiwan", key: "tw", value: "tw" },
  { text: "Tajikistan", key: "tj", value: "tj" },
  { text: "Tanzania", key: "tz", value: "tz" },
  { text: "Thailand", key: "th", value: "th" },
  { text: "Timorleste", key: "tl", value: "tl" },
  { text: "Togo", key: "tg", value: "tg" },
  { text: "Tokelau", key: "tk", value: "tk" },
  { text: "Tonga", key: "to", value: "to" },
  { text: "Trinidad", key: "tt", value: "tt" },
  { text: "Tunisia", key: "tn", value: "tn" },
  { text: "Turkey", key: "tr", value: "tr" },
  { text: "Turkmenistan", key: "tm", value: "tm" },
  { text: "Tuvalu", key: "tv", value: "tv" },
  { text: "U.A.E.", key: "ae", value: "ae", alias: "United Arab Emirates" },
  { text: "Uganda", key: "ug", value: "ug" },
  { text: "Ukraine", key: "ua", value: "ua" },
  { text: "United Kingdom", key: "uk", value: "uk", alias: "uk" },
  { text: "United States", key: "us", value: "us", alias: "America" },
  { text: "Uruguay", key: "uy", value: "uy" },
  { text: "US Minor Islands", key: "um", value: "um" },
  { text: "US Virgin Islands", key: "vi", value: "vi" },
  { text: "Uzbekistan", key: "uz", value: "uz" },
  { text: "Vanuatu", key: "vu", value: "vu" },
  { text: "Vatican City", key: "va", value: "va" },
  { text: "Venezuela", key: "ve", value: "ve" },
  { text: "Vietnam", key: "vn", value: "vn" },
  { text: "Wales", key: "wls", value: "wls" },
  { text: "Wallis and Futuna", key: "wf", value: "wf" },
  { text: "Western Sahara", key: "eh", value: "eh" },
  { text: "Yemen", key: "ye", value: "ye" },
  { text: "Zambia", key: "zm", value: "zm" },
  { text: "Zimbabwe", key: "zw", value: "zw" }
];
const BLOOD_GROUP_OPTIONS = [
  { key: "A+", text: "A+", value: "A+" },
  { key: "A-", text: "A-", value: "A-" },
  { key: "B+", text: "B+", value: "B+" },
  { key: "B-", text: "B-", value: "B-" },
  { key: "O+", text: "O+", value: "O+" },
  { key: "O-", text: "O-", value: "O-" },
  { key: "AB+", text: "AB+", value: "AB+" },
  { key: "AB-", text: "AB-", value: "AB-" }
];
const MARITAL_STATUS_OPTIONS = [
  { key: "single", text: "Single", value: "Single" },
  { key: "married", text: "Married", value: "Married" },
  { key: "divorced", text: "Divorced", value: "Divorced" }
];
const CITY_OPTIONS = [
  { key: "city1", value: "City1", text: "City1" },
  { key: "city2", value: "City2", text: "City2" }
];
const TYPE_OPTIONS = [
  { key: "mobile", text: "Mobile", value: "Mobile" },
  { key: "landline", text: "Landline", value: "Landline" },
  { key: "email", text: "Email", value: "Email" }
];
const EMPLOYEE_STATUS_OPTIONS = [
  { key: "permanent", text: "Permanent", value: "Permanent" },
  { key: "intern", text: "Intern", value: "Intern" },
  { key: "freelancer", text: "Freelancer", value: "Freelancer" },
  { key: "contractual", text: "Contractual", value: "Contractual" }
];
const DEPARTMENT_OPTIONS = [
  { key: "department1", text: "Department1", value: "Department1" },
  { key: "department2", text: "Department2", value: "Department2" }
];
const MODE_OF_PAYMENT_OPTIONS = [
  { key: "bankTransfer", text: "Bank Transfer", value: "Bank Transfer" },
  { key: "cash", text: "Cash", value: "Cash" }
];
const RELATION_OPTIONS = [
  { key: "father", text: "Father", value: "Father" },
  { key: "mother", text: "Mother", value: "Mother" },
  { key: "sibling", text: "Sibling", value: "Sibling" },
  { key: "wife", text: "Wife", value: "Wife" },
  { key: "husband", text: "Husband", value: "Husband" },
  { key: "son", text: "Son", value: "Son" },
  { key: "daughter", text: "Daughter", value: "Daughter" }
];
const COMPANY_ASSETS_OPTIONS = [
  { key: "asset1", text: "Asset1", value: "Asset1" },
  { key: "asset2", text: "Asset2", value: "Asset2" }
];
const FREQUENCY_OPTIONS = [
  { key: "daily", text: "Daily", value: "Daily" },
  { key: "weekly", text: "Weekly", value: "Weekly" },
  { key: "monthly", text: "Monthly", value: "Monthly" },
  { key: "yearly", text: "Yearly", value: "Yearly" }
];
export {
  MONGO_URL,
  NODE_ENV,
  GENDER_OPTIONS,
  BLOOD_GROUP_OPTIONS,
  MARITAL_STATUS_OPTIONS,
  CITY_OPTIONS,
  COUNTRY_OPTIONS,
  TYPE_OPTIONS,
  EMPLOYEE_STATUS_OPTIONS,
  MODE_OF_PAYMENT_OPTIONS,
  RELATION_OPTIONS,
  COMPANY_ASSETS_OPTIONS,
  FREQUENCY_OPTIONS,
  DEPARTMENT_OPTIONS
};
